name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t "ghcr.io/lemon-mint/timeserver:${GITHUB_REF#refs/*/}" .
    
    - name: Push image
      run: |
        docker login ghcr.io -u lemon-mint --password ${{ secrets.GITHUB_TOKEN }}
        docker push "ghcr.io/lemon-mint/timeserver:${GITHUB_REF#refs/*/}"
        docker tag "ghcr.io/lemon-mint/timeserver:${GITHUB_REF#refs/*/}" "ghcr.io/lemon-mint/timeserver:latest"
        docker push "ghcr.io/lemon-mint/timeserver:latest"
