name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: imjasonh/setup-ko@v0.6

    - name: ko build
      env:
        KO_DOCKER_REPO: ghcr.io/lemon-mint/timeserver
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ko build --tags "${GITHUB_REF#refs/*/},latest" .
